SRC =	main.cpp Animal.cpp Dog.cpp Cat.cpp \
		WrongCat.cpp WrongAnimal.cpp \
		Brain.cpp

OBJ = $(SRC:.cpp=.o)

CXX = c++

NAME = Animal

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
